_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: '/home/bong08/lib/ms/detectron2/2021_03_11/model_final.pth' # "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 3
#  INPUT:
#    MIN_SIZE_TRAIN: (270, 306, 360, 396, 450, 540)
#    MIN_SIZE_TRAIN_SAMPLING: "choice"
#    MIN_SIZE_TEST: 360
#    MAX_SIZE_TRAIN: 960
#    MAX_SIZE_TEST: 640
  #  CROP:
  #    ENABLED: True
DATASETS:
  TRAIN: ("car_train",)
  TEST: ("car_val",)
SOLVER:
  STEPS: (25000, 30000)
  MAX_ITER: 40000
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "./2021_03_11"